name: Build and deploy .NET Core application to Web App icollector
on:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: icollector
  AZURE_WEBAPP_PACKAGE_PATH: /home/runner/work/ICollector/ICollector.Server/publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: ICollector.Server
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build

    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --property:PublishDir="${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Install EF tool
      run: |
        dotnet new tool-manifest
        dotnet tool install dotnet-ef

    - name: Generate migration scripts
      run: |
        dotnet ef migrations script --output "${{ env.WORKING_DIRECTORY }}/Migrations/script1.sql" -c AppIdentityDbContext --idempotent --no-build
        dotnet ef migrations script --output "${{ env.WORKING_DIRECTORY }}/Migrations/script2.sql" -c ApplicationDbContext --idempotent --no-build

    - name: Migrate IdentityDB
      uses: Azure/sql-action@v2.2
      with:
        connection-string: ${{ secrets.MSSQL_CONNECTION_STRING }}
        sql-script: "${{ env.WORKING_DIRECTORY }}/Migrations/script1.sql"

    - name: Migrate ApplicationDB
      uses: azure/sql-action@v2.2
      with:
        connection-string: ${{ secrets.MSSQL_CONNECTION_STRING }}
        sql-script: "${{ env.WORKING_DIRECTORY }}/Migrations/script2.sql"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.icollector_5647 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
